### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by xiaobeifeng** [HawkingOuYang/GestureLock-And-Touch-ID#2]
我想学习下您把锁屏界面加在应用上的思路，可否介绍一下，谢谢您了

**Comment by HawkingOuYang** [comment]
你这句话逻辑不通吧，只是用英语介绍一下

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.7.29&pv=9.2.1&source=email_footer_2]
On 周二, 4月 19, 2016 at 08:42, xiaobeifeng notifications@github.com wrote:
我想学习下您把锁屏界面加在英语上的思路，可否介绍一下，谢谢您了

**Comment by xiaobeifeng** [comment]
我已经更正了，一激动就写错了，原谅我~~~

**Comment by HawkingOuYang** [comment]
看我代码，更清楚。这说来话长啊。
Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.7.29&pv=9.2.1&source=email_footer_2]
On 周二, 4月 19, 2016 at 08:53, xiaobeifeng notifications@github.com wrote:
我已经更正了，一激动就写错了，原谅我~~~

**Comment by xiaobeifeng** [comment]
您在应用从前台进入活跃状态调出锁屏界面，然后解锁后锁屏视图是如何移除的呢

发自我的 iPhone

> 在 2016年4月19日，上午8:56，HawkingOuYang notifications@github.com 写道：
> 
> 看我代码，更清楚。这说来话长啊。
> Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.7.29&pv=9.2.1&source=email_footer_2]

**Comment by HawkingOuYang** [comment]
关键点: 1. 自定义UiWindow，级别至少是UIWindowAlertLevel 2. 用这个Window模态弹出，再模态dismiss

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.7.29&pv=9.2.1&source=email_footer_2]
On 周二, 4月 19, 2016 at 08:58, xiaobeifeng notifications@github.com wrote:
您在应用从前台进入活跃状态调出锁屏界面，然后解锁后锁屏视图是如何移除的呢

发自我的 iPhone

> 在 2016年4月19日，上午8:56，HawkingOuYang notifications@github.com 写道：
> 
> 看我代码，更清楚。这说来话长啊。
> Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.7.29&pv=9.2.1&source=email_footer_2]

**Comment by xiaobeifeng** [comment]
UIWindowAlertLevel 2这块没听过，我查些资料，一直就困惑在这里，多谢您的解答，给您添麻烦了

**Comment by HawkingOuYang** [comment]
其一:
Status 级别，电池栏。 Alert 级别，时间 信号 闹钟 等。 normal 级别，平时用得最多的。
其二: Window级别越高，视图(window继承view,也是视图) 层级越高，离屏幕越远。 级别高的window，覆盖级别低的window.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.7.29&pv=9.2.1&source=email_footer_2]
On 周二, 4月 19, 2016 at 09:10, xiaobeifeng notifications@github.com wrote:
UIWindowAlertLevel 2这块没听过，我查些资料，一直就困惑在这里，多谢您的解答，给您添麻烦了
